"""empty message

Revision ID: 11dfa7923aa5
Revises: 52857a4340fb
Create Date: 2023-12-21 11:27:04.733721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11dfa7923aa5'
down_revision = '52857a4340fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tip_event', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('link_protokol', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('link_protokol')
        batch_op.drop_column('tip_event')

    # ### end Alembic commands ###
