"""empty message

Revision ID: 52857a4340fb
Revises: 
Create Date: 2023-12-20 11:47:07.440008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52857a4340fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('link', sa.String(length=120), nullable=True),
    sa.Column('logo', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('fam', sa.String(length=128), nullable=True),
    sa.Column('nam', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('site_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_user_name'), ['name'], unique=True)

    op.create_table('event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('logo', sa.String(length=120), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('len_dist', sa.Float(), nullable=True),
    sa.Column('time_result', sa.String(length=15), nullable=True),
    sa.Column('link_event', sa.String(length=120), nullable=True),
    sa.Column('my_review', sa.Text(), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    with op.batch_alter_table('site_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_user_name'))

    op.drop_table('site_user')
    op.drop_table('organizer')
    op.drop_table('location')
    # ### end Alembic commands ###
